### ISSUE TITLE
Wrong sidebar height on page-adminpage

### ISSUE THREAD

**Issue by rjgamer** [Neoflow/Fraggy-Backend-Theme#14]
Source: 
https://forum.wbce.org/viewtopic.php?pid=6269#p6269

**Comment by Colinax** [comment]
The select2 Script is slower than the Script for the height detection of the navbar (i think it).

At the Desktop view, the height detection Script calculates for the first loadtime the height for the Tablet view. After a viewport resize (open and/or close the console), the Script calculates the correct height.

**Comment by rjgamer** [comment]
Fixed in v2.0 branch for WBCE v1.2

**Comment by rjgamer** [comment]
v1.5 didn't really fixed the hight of the sidebar. But the new fix in the next coming patch release v1.5.1 will fix it finally. Sorry!
