### ISSUE TITLE
sysinfo.php is loaded twice times on media-adminpage

### ISSUE THREAD

**Issue by Colinax** [Neoflow/Fraggy-Backend-Theme#15]
Source: 
Browser Console
![sysinfo](https://cloud.githubusercontent.com/assets/22152866/18442431/0256f9b8-7911-11e6-8db7-a1ae3c247004.jpg)

**Comment by rjgamer** [comment]
I will check it. Maybe it has something to do with the js-based workarounds to get a well done media page with bootstrap.

**Comment by rjgamer** [comment]
Fixed in v2.0 branch for WBCE v1.2
