### ISSUE TITLE
Update Jquery to 2.2.4

### ISSUE THREAD

**Issue by Colinax** [Neoflow/Fraggy-Backend-Theme#16]
There have been fixed some important bugs e.g. compatibility bugs with 1.x

Source:
https://github.com/jquery/jquery/compare/2.2.2...2.2.4
http://blog.jquery.com/

**Comment by rjgamer** [comment]
Planned for next patch release, with low priority.

**Comment by rjgamer** [comment]
Fixed in v2.0 branch for WBCE v1.2
