### ISSUE TITLE
A Bootstrap update changes some colors

### ISSUE THREAD

**Issue by Colinax** [Neoflow/Fraggy-Backend-Theme#17]
A Bootstrap update to 3.3.7 has the effect to change some link and background-colors.

On the left side of the photo Bootstrap 3.3.6, on the right side is Bootstrap 3.3.7 active.
![bootstrap_small](https://cloud.githubusercontent.com/assets/22152866/18443976/9b2755ec-7917-11e6-8f09-bbe047453da6.jpg)

**Comment by rjgamer** [comment]
Dont change bootstrap by yourself. Fraggys Bootstrap is customized with SASS. But thanks I will update to the latest version.

**Comment by rjgamer** [comment]
Fixed in v2.0 branch for WBCE v1.2
