### ISSUE TITLE
Bottom captions may cause confusion within modules

### ISSUE THREAD

**Issue by mrbaseman** [Neoflow/Fraggy-Backend-Theme#28]
Fraggy uses captions and places them at the bottom with
`caption-side: bottom;`
Modules may use captions as well and rely on the default behavior that the caption is something like a heading.
Maybe Fraggy can add a class to the tables that shall have the caption in the bottom and apply the caption-side: bottom only to that class.
MPform was affected by this issue but has fixed it locally. However, other modules might be affected, too.

**Comment by rjgamer** [comment]
Thanks for your information. Do you have a code example for a better/easier reproduction?
