### ISSUE TITLE
z-index bug with topics

### ISSUE THREAD

**Issue by Nostromio** [Neoflow/Fraggy-Backend-Theme#29]
I've found a z-index bug in combination with topics, look at the screenshot

![Screenshot 2019-04-30 23 03 23](https://user-images.githubusercontent.com/49448710/56993538-033ede00-6b9d-11e9-9dbb-17c3198a1191.png)

**Comment by rjgamer** [comment]
It's more a problem of Topics than of Fraggy. If possible I would to prevent to add "design fixes" for third-party modules.

**Comment by Nostromio** [comment]
Sure ... but ... why is this issue not existend in WBCE Flat Backend Theme if its topics fault?

**Comment by rjgamer** [comment]
I will see what I can fix for the next release.
